/**
 * Nombres semánticos de ícono usados en todo el dominio — desacoplados de la
 * librería de íconos concreta (hoy `lucide-react-native`, ver `components/Icon.tsx`,
 * que mapea cada uno de estos nombres a su componente Lucide). Vive en `domain`
 * (no en `components`) para que archivos de dominio puros como `quickAdd.ts` y
 * los mappers de `features/*` puedan tipar sus campos `icon` sin depender de
 * la capa de componentes.
 */
export type IconName =
  | 'add'
  | 'calendar-month'
  | 'calendar-today'
  | 'event'
  | 'check'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-down'
  | 'chevron-up'
  | 'close'
  | 'cloud'
  | 'delete-outline'
  | 'description'
  | 'equalizer'
  | 'graphic-eq'
  | 'favorite'
  | 'flag'
  | 'folder'
  | 'inbox'
  | 'language'
  | 'light-mode'
  | 'link'
  | 'menu'
  | 'mic'
  | 'north-east'
  | 'notifications'
  | 'pause'
  | 'photo-camera'
  | 'photo-library'
  | 'play-arrow'
  | 'repeat'
  | 'schedule'
  | 'search'
  | 'settings'
  | 'stop'
  | 'sticky-note-2'
  | 'sync-alt'
  | 'undo'
  | 'view-day'
  | 'view-week'
  | 'view-grid'
  | 'filter-list'
  // Métricas de Auto-registro (`domain/healthMetrics.ts`)
  | 'footprints'
  | 'timer'
  | 'flame'
  | 'bed'
  | 'zap'
  | 'watch'
  | 'award'
  | 'activity'
  | 'trending-up'
  | 'person-standing'
  | 'bike'
  | 'dumbbell'
  | 'waves-horizontal'
  | 'sunrise'
  | 'sun'
  | 'more-horiz'
  | 'palette'
  | 'rows'
  | 'check-circle'
  | 'sparkles'
  | 'checklist'
  // Set de íconos elegibles al crear/editar una categoría (Ajustes >
  // Categorías, ver `components/settings/CategoryFormModal.tsx`)
  | 'briefcase'
  | 'person'
  | 'book-open'
  | 'home'
  | 'star'
  | 'cart'
  | 'music'
  | 'plane';
