import React from 'react';
import {
  Plus,
  Calendar,
  CalendarDays,
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Cloud,
  Trash2,
  FileText,
  AudioLines,
  AudioWaveform,
  Heart,
  Flag,
  Folder,
  Inbox,
  Languages,
  Sun,
  Link2,
  Menu,
  Mic,
  ArrowUpRight,
  Bell,
  Pause,
  Camera,
  Images,
  Play,
  Repeat,
  Clock,
  Search,
  Settings,
  Square,
  StickyNote,
  RefreshCw,
  Undo2,
  LayoutList,
  CalendarRange,
  LayoutGrid,
  ListFilter,
  Footprints,
  Timer,
  Flame,
  Bed,
  Zap,
  Watch,
  Award,
  Activity,
  TrendingUp,
  PersonStanding,
  Bike,
  Dumbbell,
  WavesHorizontal,
  Sunrise,
  MoreHorizontal,
  Palette,
  Rows3,
  CheckCircle2,
  Sparkles,
  ListChecks,
  Briefcase,
  User,
  BookOpen,
  House,
  Star,
  ShoppingCart,
  Music,
  Plane,
  type LucideIcon,
} from 'lucide-react-native';
import type { IconName } from '@/domain/iconNames';

export type { IconName };

const ICON_MAP: Record<IconName, LucideIcon> = {
  add: Plus,
  'calendar-month': Calendar,
  'calendar-today': CalendarDays,
  event: CalendarClock,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  close: X,
  cloud: Cloud,
  'delete-outline': Trash2,
  description: FileText,
  equalizer: AudioLines,
  'graphic-eq': AudioWaveform,
  favorite: Heart,
  flag: Flag,
  folder: Folder,
  inbox: Inbox,
  language: Languages,
  'light-mode': Sun,
  link: Link2,
  menu: Menu,
  mic: Mic,
  'north-east': ArrowUpRight,
  notifications: Bell,
  pause: Pause,
  'photo-camera': Camera,
  'photo-library': Images,
  'play-arrow': Play,
  repeat: Repeat,
  schedule: Clock,
  search: Search,
  settings: Settings,
  stop: Square,
  'sticky-note-2': StickyNote,
  'sync-alt': RefreshCw,
  undo: Undo2,
  'view-day': LayoutList,
  'view-week': CalendarRange,
  'view-grid': LayoutGrid,
  'filter-list': ListFilter,
  footprints: Footprints,
  timer: Timer,
  flame: Flame,
  bed: Bed,
  zap: Zap,
  watch: Watch,
  award: Award,
  activity: Activity,
  'trending-up': TrendingUp,
  'person-standing': PersonStanding,
  bike: Bike,
  dumbbell: Dumbbell,
  'waves-horizontal': WavesHorizontal,
  sunrise: Sunrise,
  sun: Sun,
  'more-horiz': MoreHorizontal,
  palette: Palette,
  rows: Rows3,
  'check-circle': CheckCircle2,
  sparkles: Sparkles,
  checklist: ListChecks,
  briefcase: Briefcase,
  person: User,
  'book-open': BookOpen,
  home: House,
  star: Star,
  cart: ShoppingCart,
  music: Music,
  plane: Plane,
};

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: React.ComponentProps<LucideIcon>['style'];
}

/** Wrapper único sobre `lucide-react-native` — mantiene los mismos nombres
 * semánticos de ícono que se usaban con `MaterialIcons` (`name="check"`, etc.)
 * para minimizar el diff de la migración, pero desacopla el resto del código
 * de la librería de íconos concreta. */
export function Icon({ name, size = 20, color, strokeWidth = 2, style }: IconProps) {
  const LucideComponent = ICON_MAP[name];
  return <LucideComponent size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
