import type { CategoryId, HabitSchedule, ItemType, PriorityLevel, SeedTitles } from './model';

// Textos de la demo interactiva (la pantalla Hoy dentro del teléfono). Mismo
// vocabulario que la app (`src/i18n/translations.ts`), español neutro.

const es = {
  phoneLabel: 'Demo interactiva de la pantalla Hoy de Meld',
  hint: 'Pruébalo: es la app de verdad. Agrega, completa, desliza…',
  today: 'Hoy',
  tomorrow: 'Mañana',
  yesterday: 'Ayer',
  weekdays: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  months: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
  doneOf: '{done} de {total} hechos',
  search: 'Buscar',
  searchPlaceholder: 'Buscar en todos tus días…',
  noResults: 'Sin resultados',
  group: 'Agrupar por tipo',
  more: 'Próximos recordatorios',
  prevDay: 'Día anterior',
  nextDay: 'Día siguiente',
  backToToday: 'Volver a hoy',
  menu: 'Menú',
  closeMenu: 'Cerrar menú',
  destinations: ['Hoy', 'Bandeja', 'Calendario', 'Momentos', 'Ajustes'],
  inAppOnly: 'Esta pantalla está en la app. Únete a la lista para probarla completa.',
  add: 'Agregar',
  byVoice: 'Por voz',
  byText: 'Por texto',
  emptyToday: 'Nada agendado para hoy',
  emptyDay: 'Nada agendado este día',
  emptyHint: 'Toca + para agregar algo.',
  undo: 'Deshacer',
  undoTask: 'Tarea completada',
  undoHabit: 'Hábito completado',
  undoDeleted: 'Ítem eliminado',
  delete: 'Eliminar',
  markDone: 'Marcar como hecho',
  play: 'Reproducir',
  pause: 'Pausar',
  edit: 'Editar',
  types: { task: 'Tarea', event: 'Evento', habit: 'Hábito', note: 'Nota', voiceMemo: 'Nota de voz' } as Record<ItemType, string>,
  groups: { event: 'Eventos', task: 'Tareas', habit: 'Hábitos', note: 'Notas', voiceMemo: 'Audios' } as Record<ItemType, string>,
  newTitle: { task: 'Nueva tarea', event: 'Nuevo evento', habit: 'Nuevo hábito', note: 'Nueva nota', voiceMemo: 'Nueva nota de voz' } as Record<ItemType, string>,
  saveNew: { task: 'Agregar tarea', event: 'Agregar evento', habit: 'Agregar hábito', note: 'Agregar nota', voiceMemo: 'Agregar nota de voz' } as Record<ItemType, string>,
  saveEdit: { task: 'Actualizar tarea', event: 'Actualizar evento', habit: 'Actualizar hábito', note: 'Actualizar nota', voiceMemo: 'Actualizar nota de voz' } as Record<ItemType, string>,
  close: 'Cerrar',
  titlePlaceholder: '¿Qué tienes que hacer?',
  notePlaceholder: 'Escribe una nota…',
  day: 'Día',
  remindMe: 'Recordarme',
  starts: 'Empieza',
  duration: 'Duración',
  off: 'Apagado',
  frequency: 'Frecuencia',
  priority: 'Prioridad',
  category: 'Categoría',
  noneCategory: 'Ninguna',
  priorities: { none: 'Ninguna', low: 'Baja', medium: 'Media', high: 'Alta' } as Record<PriorityLevel, string>,
  categories: { Work: 'Trabajo', Personal: 'Personal', Health: 'Salud' } as Record<CategoryId, string>,
  schedules: { 'Every day': 'Todos los días', Weekdays: 'Días de semana', '3x a week': '3 veces por semana', Weekly: 'Semanal' } as Record<HabitSchedule, string>,
  durations: [
    [30, '30 min'],
    [60, '1 h'],
    [90, '1 h 30'],
    [120, '2 h'],
  ] as [number, string][],
  record: 'Toca para grabar',
  recording: 'Grabando',
  stop: 'Detener',
  discard: 'Descartar y volver a grabar',
  micError: 'No pudimos usar el micrófono. Revisa el permiso del navegador.',
  recordFirst: 'Graba algo para poder guardar.',
  listening: 'Escuchando…',
  speakHint: 'Prueba: “reunión con Ana el viernes a las 4”',
  tapToStop: 'Toca el micrófono para terminar',
  heardNothing: 'No te escuché. Inténtalo de nuevo.',
  voiceError: 'El dictado no está disponible en este navegador.',
  retry: 'Reintentar',
  cancel: 'Cancelar',
  remindersTitle: 'Próximos recordatorios',
  remindersEmpty: 'No hay recordatorios próximos.',
  seed: {
    q3: 'Revisar números del Q3',
    dentist: 'Llamar al dentista',
    lunch: 'Almuerzo con Ana',
    idea: 'Idea para la landing',
    read: 'Leer 20 minutos',
    steps: '10.000 pasos',
    proposal: 'Enviar propuesta',
    standup: 'Reunión de equipo',
    trip: 'Ideas para el viaje',
  } as SeedTitles,
  widgets: { today: 'Hoy', habits: 'Hábitos', allDone: '¡Todo hecho por hoy!', noHabits: 'Sin hábitos para hoy' },
  qa: {
    placeholder: {
      task: '¿Qué hay que hacer?',
      event: '¿Qué está pasando?',
      voiceMemo: 'Nombra esta grabación',
      note: '¿Qué tienes en mente?',
      habit: '¿Qué quieres mantener?',
    },
    notePlaceholderBody: 'Escribe una nota…',
    dictate: 'Dictar el título',
    fieldDay: 'Día',
    fieldRemindMe: 'Recordarme',
    fieldStarts: 'Empieza',
    fieldDuration: 'Duración',
    fieldRepeat: 'Repetir',
    fieldEarlyAlert: 'Alerta previa',
    fieldSchedule: 'Frecuencia',
    fieldPreferredTime: 'Hora preferida',
    fieldAutoTrack: 'Auto-registro',
    fieldCategory: 'Categoría',
    fieldPriority: 'Prioridad',
    fieldLink: 'Pegar un enlace (opcional)',
    openLink: 'Abrir enlace',
    anyTime: 'Cualquier hora',
    selectTime: 'Elige una hora',
    selectDate: 'Elige un día',
    selectDuration: 'Elige la duración',
    confirm: 'Confirmar',
    repeatOptions: { Never: 'Nunca', Daily: 'Diario', Weekly: 'Semanal', Monthly: 'Mensual' } as Record<string, string>,
    earlyAlertOptions: {
      Off: 'Apagado',
      '10 min before': '10 min antes',
      '30 min before': '30 min antes',
      '1 hr before': '1 h antes',
    } as Record<string, string>,
    preferredTimeOptions: { Anytime: 'Cualquier hora', Morning: 'Mañana', Afternoon: 'Tarde', Evening: 'Noche' } as Record<string, string>,
    none: 'Ninguna',
    health: {
      title: 'Auto-registro',
      proNote: 'Con el plan Pro, al conectar Apple Health o Google Fit este check se marca solo apenas cumplas la meta ahí. Por ahora, márcalo a mano.',
      groups: { activity: 'ACTIVIDAD', rings: 'ANILLOS', workouts: 'ENTRENAMIENTOS' } as Record<string, string>,
      units: { steps: 'pasos', min: 'min', cal: 'kcal', hours: 'h' } as Record<string, string>,
      metrics: {
        steps: 'Pasos',
        exerciseMinutes: 'Minutos de ejercicio',
        activeEnergy: 'Energía activa',
        sleep: 'Sueño',
        moveRing: 'Anillo de movimiento cerrado',
        exerciseRing: 'Anillo de ejercicio cerrado',
        standRing: 'Anillo de pie cerrado',
        allRings: 'Los tres anillos',
        anyWorkout: 'Cualquier entrenamiento',
        running: 'Correr',
        walking: 'Caminar',
        cycling: 'Ciclismo',
        strengthTraining: 'Entrenamiento de fuerza',
        swimming: 'Natación',
        yoga: 'Yoga',
      } as Record<string, string>,
    },
    weekdayHeader: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
    recordingLabel: 'Grabando',
    pause: 'Pausar',
    resume: 'Reanudar',
    stop: 'Detener',
    discardRecording: 'Descartar y volver a grabar',
    tapToRecord: 'Toca para grabar',
  },

};

export type DemoStrings = typeof es;

const en: DemoStrings = {
  phoneLabel: "Interactive demo of Meld's Today screen",
  hint: "Try it: it's the real app. Add, complete, swipe…",
  today: 'Today',
  tomorrow: 'Tomorrow',
  yesterday: 'Yesterday',
  weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  doneOf: '{done} of {total} done',
  search: 'Search',
  searchPlaceholder: 'Search all your days…',
  noResults: 'No results',
  group: 'Group by type',
  more: 'Upcoming reminders',
  prevDay: 'Previous day',
  nextDay: 'Next day',
  backToToday: 'Back to today',
  menu: 'Menu',
  closeMenu: 'Close menu',
  destinations: ['Today', 'Inbox', 'Calendar', 'Moments', 'Settings'],
  inAppOnly: 'This screen lives in the app. Join the waitlist to try all of it.',
  add: 'Add',
  byVoice: 'By voice',
  byText: 'By text',
  emptyToday: 'Nothing scheduled for today',
  emptyDay: 'Nothing scheduled this day',
  emptyHint: 'Tap + to add something.',
  undo: 'Undo',
  undoTask: 'Task completed',
  undoHabit: 'Habit completed',
  undoDeleted: 'Item deleted',
  delete: 'Delete',
  markDone: 'Mark as done',
  play: 'Play',
  pause: 'Pause',
  edit: 'Edit',
  types: { task: 'Task', event: 'Event', habit: 'Habit', note: 'Note', voiceMemo: 'Voice memo' },
  groups: { event: 'Events', task: 'Tasks', habit: 'Habits', note: 'Notes', voiceMemo: 'Voice memos' },
  newTitle: { task: 'New task', event: 'New event', habit: 'New habit', note: 'New note', voiceMemo: 'New voice memo' },
  saveNew: { task: 'Add task', event: 'Add event', habit: 'Add habit', note: 'Add note', voiceMemo: 'Add voice memo' },
  saveEdit: { task: 'Update task', event: 'Update event', habit: 'Update habit', note: 'Update note', voiceMemo: 'Update voice memo' },
  close: 'Close',
  titlePlaceholder: 'What do you need to do?',
  notePlaceholder: 'Write a note…',
  day: 'Day',
  remindMe: 'Remind me',
  starts: 'Starts',
  duration: 'Duration',
  off: 'Off',
  frequency: 'Frequency',
  priority: 'Priority',
  category: 'Category',
  noneCategory: 'None',
  priorities: { none: 'None', low: 'Low', medium: 'Medium', high: 'High' },
  categories: { Work: 'Work', Personal: 'Personal', Health: 'Health' },
  schedules: { 'Every day': 'Every day', Weekdays: 'Weekdays', '3x a week': '3x a week', Weekly: 'Weekly' },
  durations: [
    [30, '30 min'],
    [60, '1 hr'],
    [90, '1.5 hr'],
    [120, '2 hr'],
  ],
  record: 'Tap to record',
  recording: 'Recording',
  stop: 'Stop',
  discard: 'Discard and record again',
  micError: "We couldn't use the microphone. Check the browser permission.",
  recordFirst: 'Record something to save it.',
  listening: 'Listening…',
  speakHint: 'Try: “meeting with Ana on Friday at 4”',
  tapToStop: 'Tap the mic to finish',
  heardNothing: "I didn't catch that. Try again.",
  voiceError: "Dictation isn't available in this browser.",
  retry: 'Try again',
  cancel: 'Cancel',
  remindersTitle: 'Upcoming reminders',
  remindersEmpty: 'No upcoming reminders.',
  seed: {
    q3: 'Review the Q3 numbers',
    dentist: 'Call the dentist',
    lunch: 'Lunch with Ana',
    idea: 'Idea for the landing page',
    read: 'Read 20 minutes',
    steps: '10,000 steps',
    proposal: 'Send the proposal',
    standup: 'Team meeting',
    trip: 'Trip ideas',
  },
  widgets: { today: 'Today', habits: 'Habits', allDone: 'All done for today!', noHabits: 'No habits today' },
  qa: {
    placeholder: {
      task: 'What needs doing?',
      event: 'What is happening?',
      voiceMemo: 'Name this recording',
      note: 'What is on your mind?',
      habit: 'What do you want to keep up?',
    },
    notePlaceholderBody: 'Write a note…',
    dictate: 'Dictate the title',
    fieldDay: 'Day',
    fieldRemindMe: 'Remind me',
    fieldStarts: 'Starts',
    fieldDuration: 'Duration',
    fieldRepeat: 'Repeat',
    fieldEarlyAlert: 'Early alert',
    fieldSchedule: 'Schedule',
    fieldPreferredTime: 'Preferred time',
    fieldAutoTrack: 'Auto-track',
    fieldCategory: 'Category',
    fieldPriority: 'Priority',
    fieldLink: 'Paste a link (optional)',
    openLink: 'Open link',
    anyTime: 'Any time',
    selectTime: 'Select a time',
    selectDate: 'Select a date',
    selectDuration: 'Select a duration',
    confirm: 'Confirm',
    repeatOptions: { Never: 'Never', Daily: 'Daily', Weekly: 'Weekly', Monthly: 'Monthly' },
    earlyAlertOptions: { Off: 'Off', '10 min before': '10 min before', '30 min before': '30 min before', '1 hr before': '1 hr before' },
    preferredTimeOptions: { Anytime: 'Anytime', Morning: 'Morning', Afternoon: 'Afternoon', Evening: 'Evening' },
    none: 'None',
    health: {
      title: 'Auto-track',
      proNote: 'With the Pro plan, once you connect Apple Health or Google Fit this check marks itself as soon as you hit the goal there. For now, tick it yourself.',
      groups: { activity: 'ACTIVITY', rings: 'RINGS', workouts: 'WORKOUTS' },
      units: { steps: 'steps', min: 'min', cal: 'kcal', hours: 'h' },
      metrics: {
        steps: 'Steps',
        exerciseMinutes: 'Exercise minutes',
        activeEnergy: 'Active energy',
        sleep: 'Sleep',
        moveRing: 'Move ring closed',
        exerciseRing: 'Exercise ring closed',
        standRing: 'Stand ring closed',
        allRings: 'All three rings',
        anyWorkout: 'Any workout',
        running: 'Running',
        walking: 'Walking',
        cycling: 'Cycling',
        strengthTraining: 'Strength training',
        swimming: 'Swimming',
        yoga: 'Yoga',
      },
    },
    weekdayHeader: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    recordingLabel: 'Recording',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    discardRecording: 'Discard and record again',
    tapToRecord: 'Tap to record',
  },

};

export const demoStrings = { es, en };
